### ISSUE TITLE
Prove properties

### ISSUE THREAD

**Issue by leesoons** [NASA-SW-VnV/CoCoSim#11]
Hi,
A counterexample was returned when checking the FRETISH specification with Cocosim, but the counter-example does not seem to prove that the property is violated. The following are the models, specifications, and corresponding counterexamples.
![image](https://user-images.githubusercontent.com/31675243/163303024-b981bdbc-f5db-4d7f-ad6a-5de8d0eefac2.png)
![image](https://user-images.githubusercontent.com/31675243/163303049-7855f9d4-622e-49da-8946-7137de0615ad.png)
![image](https://user-images.githubusercontent.com/31675243/163300959-d92d4653-1e07-4a49-b8d6-3298ef65013b.png)
![image](https://user-images.githubusercontent.com/31675243/163303143-d0284b3d-88f1-40cc-bdca-5990fd57d34d.png)

**Comment by andreaskatis** [comment]
Hi @leesoons,

Thank you for submitting this issue. In order to try and replicate it, I need the FRET variable mapping information.

It would also be of great help if you could provide me with the Simulink / State flow model that you are using, without the imported requirement.

Andreas

**Comment by leesoons** [comment]
Thanks! The relevant documents have been sent by email

**Comment by andreaskatis** [comment]
Hi @leesoons ,

I have not received an e-mail about this. Would it be possible for you to attach the necessary information here?

Best Regards,

Andreas

**Comment by leesoons** [comment]
Sorry, these are the relevant documents for this case.
[fan_controller.zip](https://github.com/NASA-SW-VnV/CoCoSim/files/8489126/fan_controller.zip)
Thanks!

**Comment by andreaskatis** [comment]
Hi @leesoons ,

I wanted to provide you with an update. Verification of Simulink models with Stateflow constructs is still at an experimental phase. I've been looking into this for some time now, and I believe that the issue is that the FRET requirement "REQ04" is not properly translated from Simulink to Lustre, when you run "Prove Properties" in CoCoSim.

I am still working on this, as I am not 100% sure that this is indeed the issue. It could take a while to provide a fix. I will update this issue once I have a workaround, or a proper solution.

This is a very useful use case as it will help me identify potential holes in our current translation. Thank you very much for using CoCoSim!

**Comment by leesoons** [comment]
Got it! Thank you very much for your reply.

**Comment by andreaskatis** [comment]
Hi @leesoons ,

I spent some more time today on this, particularly with regards to the MATLAB version that is used. It appears that something is wrong in R2021b and R2020b when it comes to importing FRET requirements, with the result being erroneous wiring of elements in the imported contract.

In my tests I also tried out R2018b and it seems that importing works as normal with that version (wiring is correct, REQ04 is proved valid). It would be great if you could verify this on your end by trying out R2018b with this example.

Best Regards,

Andreas

**Comment by andreaskatis** [comment]
Hi @leesoons,

Just wanted to check in with you. Have you tried your example with R2018b, and if yes, did this help resolve your issue?

Thank you,

Andreas

**Comment by leesoons** [comment]
yes, thanks a lot!

**Comment by leesoons** [comment]
thanks! Here are the relevant documents




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NASA-SW-VnV/CoCoSim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NASA-SW-VnV/CoCoSim] Prove properties (Issue #11)





 
Hi @leesoons,
 
Thank you for submitting this issue. In order to try and replicate it, I need the FRET variable mapping information.
 
It would also be of great help if you could provide me with the Simulink / State flow model that you are using, without the imported requirement.
 
Andreas
