### ISSUE TITLE
“depext unmet” during installation

### ISSUE THREAD

**Issue by kumori123** [NASA-SW-VnV/CoCoSim#13]
HI，thank you all for your great work.
During installing Cocosim using ./install_CoCoSim, I met this error message "opam-depext unmet availability conditions, e.g. 'opam-version >= "2.0.0~beta5" & opam-version < "2.1"'. Is there any solution?

Thank you!

**Comment by andreaskatis** [comment]
Hi @kumori123,

Thank you for checking out CoCoSim! The error refers to the fact that you probably have a version of `opam` that is outside of the suggested range ( >= "2.0.0~beta5" & opam-version < "2.1"). As such, you would need to download and install the proper version of `opam` for the installation to go through.

Despite that, the most recent `master` branch should have worked for versions > 2.1, after which the `depext` package has been part of the default `opam` installation. If you are not using the most recent version on `master`, I would suggest trying it before installing an outdate version of `opam`.

Best Regards,

Andreas

**Comment by andreaskatis** [comment]
Hi @kumori123,

Were you able to resolve your issues? Let me know if you need further assistance.

Andreas

**Comment by kumori123** [comment]
Hi Andreas, I'm taking care of some personal business these days, I'll check your reply before next Tuesday.

**Comment by kumori123** [comment]
Hi，Andreas！
The installation script seems working after I checkout the branch into master. Thank you for your quickly reply!

**Comment by kumori123** [comment]
Hi，Andreas！
I met a new problem. It seems that the script tried to get lustrec from here: https://cavale.enseeiht.fr/git/lustrec/ which is 404 right now.
So, where can I find the latest one?
Thank you!

**Comment by andreaskatis** [comment]
Hi @kumori123,

A quick fix to address this would be to download the latest release and use the pre-built binary that exists under 'tools/verifiers/{linux, osx}/bin', by copying it under the same path in your existing installation.

Best Regards,

Andreas

**Comment by kumori123** [comment]
Hi, Andreas!
I tried the solution you mentioned above by copying binary files from CoCoSim v1.1. However, error occured like "Unable to detect the version of lustrec".
Thank you for your suggestions!

**Comment by andreaskatis** [comment]
Hi @kumori123,

Please make sure the binary is executable. You can also take a look at the installation scrip

**Comment by andreaskatis** [comment]
Hi @kumori123,

Please make sure the binary is user executable. You can also take a look at the installation script and try to manually complete each command after the ones that try to download and build lustrec.

Finally, you can also try the binary in the v1.2 and see if that will work.

The last option would be to just wait until I update the installation script on Monday (I cannot do so earlier than that, unfortunately).

Best Regards,

Andreas

**Comment by kumori123** [comment]
Hi, Andreas!
I found that only the binary of Kind2 is executable, so I modified the lustrec clone setting part in install_cocosim.sh。Concretely I turned to use the github link of lustrec with master branch. And then it seems that the installation is successful.
Thank you for your patience and tons of suggestions!

**Comment by andreaskatis** [comment]
Hi @kumori123,

I will reopen this issue for tracking reasons, since the installation script has yet to be fixed.

I am also unsure as to which version of lustrec you actually installed. Would you mind sharing the github link?
The reason I am asking is because lustrec was recently updated and its official repository moved. I'm still testing this new version, so I would not recommend trying it out just yet. If you feel like playing with it though, you can clone the repository from here:

https://github.com/Embedded-SW-VnV/lustrec

switch to the `lustrec-1.7-Xia-Huai`, and install.

Otherwise just try using the one you successfully build and see if it works for you.

Best Regards,

Andreas

**Comment by kumori123** [comment]
Hi, Andreas!
I'm using lustrec from https://github.com/coco-team/lustrec.git and master branch.
I'm going to reinstall the latest version of lustrec you mentioned.

**Comment by andreaskatis** [comment]
Hi @kumori123 ,

I wanted to let you know that I just updated the repository so that the new source for LustreC is used during installation. If you so please, feel free to install CoCoSim from a clean state using the updated script.

I will go ahead and close this issue now. Thank you!
