### ISSUE TITLE
Problems with disabled library links for CoCoSim blocks 

### ISSUE THREAD

**Issue by mfry90** [NASA-SW-VnV/CoCoSim#3]
I've recently been getting errors that seem to derive from disabled library links.  For example, when trying to "Prove properties" from the CoCoSim/examples/contract/absolute.slx, I get the following error:
![screen1b](https://user-images.githubusercontent.com/43046169/95137503-355f5280-0736-11eb-81d7-5e23439bd709.png)

When I "Check Compatibility" I see the following:
![screen2b](https://user-images.githubusercontent.com/43046169/95137521-44de9b80-0736-11eb-843a-4a9ebaa2a490.png)

Also, I see in the Simulink Library Browser two CoCoSim specification libraries, and when I try to grab a model from the first library, I get an error:
![image](https://user-images.githubusercontent.com/43046169/94973117-df41a380-04d8-11eb-8385-ff2aae041e25.png)

It appears these are all related to each other?

**Comment by hbourbouh** [comment]
We cannot check the last image you added.
Is it possible to update your `develop` branch with my latest changes and try your example again?
Before running the example, after updating the CoCoSim repo, please run in Matlab Command window:
```
install_cocosim_lib(1)
```
This will help update external CoCoSim libraries and remove some files.

To have the Matlab error, please run this in your Matlab Command window:
```
cocosim_debug = 1;
```
This will activate the debugging mode and give more details on the error.

**Comment by mfry90** [comment]
After https://github.com/NASA-SW-VnV/CoCoSim/commit/dc0a10670edd2961a8e477dce2e352afcd48d520, I'm no longer getting the same errors.  Thanks!

Oddly, I do get the same warnings (using the absolute.slx example):
```
Warning: Block diagram 'absolute_PP' contains disabled library links.  Use Model Advisor to find the disabled links in non-library models.  The diagram has been saved but may not contain what you intended. 
Warning: Block diagram 'absolute_PP' contains disabled library links.  Use Model Advisor to find the disabled links in non-library models.  The diagram has been saved but may not contain what you intended. 
Warning: Block diagram 'absolute_PP' contains disabled library links.  Use Model Advisor to find the disabled links in non-library models.  The diagram has been saved but may not contain what you intended. 
Warning: Block diagram 'absolute_PP' contains disabled library links.  Use Model Advisor to find the disabled links in non-library models.  The diagram has been saved but may not contain what you intended. 
```
I only get these warnings when I "Check Compatibility" AFTER I "Prove properties." It doesn't occur the FIRST time I "Check Compatibility".

**Comment by hbourbouh** [comment]
Thanks for checking.
Those warnings are fine. We disable library links to avoid some problems associated with block libraries' translation to Lustre.
I disabled warnings for this SaveWithDisabledLinksMsg in commit 70b8d02. It should fix the problem and you shouldn't get the same warnings anymore.
