### ISSUE TITLE
Reorder function calls in install_cocosim_lib (develop branch)

### ISSUE THREAD

**Issue by mfry90** [NASA-SW-VnV/CoCoSim#4]
install_cocosim fails when trying to do a fresh install (https://github.com/NASA-SW-VnV/CoCoSim/commit/0721fca1c37909d4865b8f4a6f8f342e5d02ef77), looks related to changing the function calls such that install_tools is now called BEFORE updateRepo, copyCoCoFiles, and copyExternalLibFiles, instead of AFTER.  When calling install_tools before, it attempts to reference functions (such as display_msg) that aren't defined until the updateRepo, copyCoCoFiles, and copyExternalLibFiles are called.

**Comment by hbourbouh** [comment]
The issue is fixed (8fe09bf).
