### ISSUE TITLE
What is "CoCoSimSpecificationLibrary/Implies" used for?

### ISSUE THREAD

**Issue by xiayu3333** [NASA-SW-VnV/CoCoSim#7]
Hello,

In Simulink's Library Browser, I see under "**CoCoSim Specification Library**" a colomn named "**Implies**" and it has "A, A==>B, B, Logical Operator, Logical Operator 1" inside it. Please see the screenshot in attachment.

I wonder what are these used for. Perhaps they are blocks of "Implies" and have been placed here by mistake?

Thanks,

Yu XIA

![Screenshot from 2021-06-03 14-53-13](https://user-images.githubusercontent.com/55579160/120648166-9d0f9e00-c47b-11eb-9217-37c8d9472964.png)

**Comment by andrewkatis** [comment]
Hello,

the actual blocks of "Implies" and "Contract" exist under "CoCoSim Specification Library" (just left-click on that to see and use the blocks). Unfolding that option simply shows a hierarchical view of the library contents.

What you actually see when clicking on the "Implies" view are essentially the atomic blocks that are essential to describe implication i.e., A => B can be expressed as  (NOT A) OR B. The same idea applies to "Contract Library" as well, where you can see the blocks that are needed to create a "Contract".

These atomic blocks are rather meaningless on their own (e.g., in "Implies" A is just an Inport and nothing more), and this may be confusing as they can still be independently imported into a model. I am currently unsure if there is a way to only display the blocks that are meant to be used. In the meantime, please consider only the blocks that appear under "CoCoSim Specification Library".

Best Regards.

Andreas

**Comment by xiayu3333** [comment]
I got it.
Thanks, Andreas!
